{{- if and .Values.portalUi.enabled .Values.portalUi.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "stillum-platform.fullname" . }}-portal-ui
  labels:
    {{- include "stillum-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal-ui
  {{- with .Values.portalUi.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.portalUi.ingress.className }}
  ingressClassName: {{ .Values.portalUi.ingress.className }}
  {{- end }}
  {{- if .Values.portalUi.ingress.tls }}
  tls:
    {{- range .Values.portalUi.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.portalUi.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "stillum-platform.fullname" $ }}-portal-ui
                port:
                  number: {{ $.Values.portalUi.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
