{{- if .Values.portalUi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stillum-platform.fullname" . }}-portal-ui
  labels:
    {{- include "stillum-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal-ui
spec:
  type: {{ .Values.portalUi.service.type }}
  ports:
    - port: {{ .Values.portalUi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stillum-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: portal-ui
{{- end }}
