{{- if .Values.publisher.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stillum-platform.fullname" . }}-publisher
  labels:
    {{- include "stillum-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: publisher
spec:
  type: {{ .Values.publisher.service.type }}
  ports:
    - port: {{ .Values.publisher.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stillum-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: publisher
{{- end }}
