{{- if .Values.registryApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stillum-platform.fullname" . }}-registry-api
  labels:
    {{- include "stillum-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry-api
spec:
  type: {{ .Values.registryApi.service.type }}
  ports:
    - port: {{ .Values.registryApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stillum-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: registry-api
{{- end }}
