{{- if .Values.runtimeGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stillum-platform.fullname" . }}-runtime-gateway
  labels:
    {{- include "stillum-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: runtime-gateway
spec:
  type: {{ .Values.runtimeGateway.service.type }}
  ports:
    - port: {{ .Values.runtimeGateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stillum-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: runtime-gateway
{{- end }}
