apiVersion: v2
name: stillum-platform
description: Stillum Business Portal â€“ deploy su Kubernetes
type: application
version: 0.0.1
appVersion: "0.0.1"
keywords:
  - stillum
  - portal
maintainers: []
